language: c

sudo: false

env:
  global:
    - LUAROCKS=2.3.0
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3
    - LUA=luajit     # latest stable version (2.0.4)
    - LUA=luajit2.0  # current head of 2.0 branch
    - LUA=luajit2.1  # current head of 2.1 branch

branches:
  only:
    - master

before_install:
  - source .travis/setenv_lua.sh
  - if [ "$(expr substr $LUA 1 6)" == "luajit" ]; then
      luarocks install ljsyscall;
    fi
  - luarocks install luafilesystem

install:
  - luarocks make rockspecs/lua-path-scm-0.rockspec

before_script:
  - luarocks install luacov
  - luarocks install lunitx

script:
  - cd test
  - lunit.sh run.lua
  - lua -lluacov test_lfs.lua

after_success:
  - luarocks install luacov-coveralls
  - luacov-coveralls

notifications:
  email:
    on_success: change
    on_failure: always
